#!/bin/bash
cat 0312_Dealer_schedule|awk '{print $1, $2, $3, $4, $5}'|grep 05:00:00" "AM
cat 0312_Dealer_schedule|awk '{print $1, $2, $3, $4, $5}'|grep 08:00:00" "AM
cat 0312_Dealer_schedule|awk '{print $1, $2, $3, $4, $5}'|grep 02:00:00" "PM
cat 0312_Dealer_schedule|awk '{print $1, $2, $3, $4, $5}'|grep 08:00:00" "PM
cat 0312_Dealer_schedule|awk '{print $1, $2, $3, $4, $5}'|grep 11:00:00" "PM

